### ISSUE TITLE
Jacoco Issue

### ISSUE THREAD

**Issue by hazendaz** [mybatis/parent#19]
@emacarron I wasn't sure what the removal was for during release.  Can you list the issue here so we can track it?

**Comment by emacarron** [comment]
Hi @hazendaz 

The Jacoco report was showing data for the packages org.apache.ibatis.ognl and org.apache.ibatis.javassist but not for the rest.

Given that jacoco is a javaagent I suppose that somethig is going wrong when running with jarjar.

**Comment by hazendaz** [comment]
@emacarron I've found in the past the 'jarjar' plugin isn't the greatest to use.  I've switched it to use the more standard maven-shade-plugin.  I've got it generating same resulting mybatis using that.  I'm going to load back in jacoco and see if that additionally solves issue.  If all is well, any issue with making this switch?

**Comment by hazendaz** [comment]
Issue is resolved.  Jacoco is properly showing mybatis items only, no ognl or javassist are shown.

**Comment by hazendaz** [comment]
Fixed with PR #20

**Comment by emacarron** [comment]
@hazendaz Should we remove all the cobertura stuff??

**Comment by hazendaz** [comment]
My original thought was to remove that in favor of jacoco.  Both seem to have their own sets of issues. We probably need to review mybatis3 results and see if they are at this moment at least reporting similar info.  If so I'm all for keeping jacoco.

--- Original Message ---

**Comment by emacarron** [comment]
I generated the site yesterday to see the results and they are good. Ognl and javassist were still showing so I excluded them in 2d079fdd397f8a801679f701188be6e05ee9fdf5.

The bad news is that our coverage when down from 80% to 78% ;) 

So I am +1 to go definitely to jacoco.
